name: Check

on:
  pull_request_target:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'read/**'

permissions:
  contents: write
  pull-requests: read


jobs:

  trigger-branch-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This ensures we get the PR content for the path check
          ref: ${{ github.event.pull_request.head.sha }}


      - name: Install dependencies for table-of-contents
        run: npm install
        working-directory: ./read
